---
version: '3'

volumes:
  postgres-data:

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:14'
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    image: 'redis:4.0.6-alpine'
    command: 'redis-server --requirepass "$REDIS_PASSWORD"'
    env_file:
      - .env
    ports:
      - '6379:6379'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    command: rabbitmq-server
    env_file:
      - .env
    ports:
      - '5672:5672'
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '5672']
      interval: 5s
      timeout: 15s
      retries: 1

  server:
    container_name: 'server'
    build: '${SERVER}'
    command: sh -c "yarn && yarn migrate && yarn start"
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - '${SERVER}:${CODE_SOURCE}/server'
      - ${CODE_SOURCE}/web-scraper-backend/node_modules/
    depends_on:
      - postgres
      - redis
      - rabbitmq

  scraper:
    container_name: 'scraper'
    build: '${SCRAPER}'
    working_dir: '${CODE_SOURCE}/scraper'
    command: bash -c "yarn start"
    env_file:
      - .env
    volumes:
      - '${SCRAPER}:${CODE_SOURCE}/scraper'
      - ${CODE_SOURCE}/node_modules/
    depends_on:
      - postgres
      - redis
      - rabbitmq
