import httpStatusCode from 'http-status-codes';

export enum ERROR_TYPES {
  NOT_FOUND = 'NOT_FOUND_ERROR',
  BAD_REQUEST = 'BAD_REQUEST_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD'
}

export const ERROR_CODES = new Map<ERROR_TYPES, number>([
  [ERROR_TYPES.NOT_FOUND, httpStatusCode.NOT_FOUND],
  [ERROR_TYPES.BAD_REQUEST, httpStatusCode.BAD_REQUEST],
  [ERROR_TYPES.UNAUTHORIZED, httpStatusCode.UNAUTHORIZED],
  [ERROR_TYPES.INTERNAL_SERVER_ERROR, httpStatusCode.INTERNAL_SERVER_ERROR],
  [ERROR_TYPES.INVALID_PAYLOAD, httpStatusCode.BAD_REQUEST]
]);
