name: Build Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup a builder for Docker build action.
      #
      # See: https://github.com/docker/setup-buildx-action
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # Add caching for docker layers.
      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      # Build the docker image.
      # See: https://github.com/docker/build-push-action
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          target: main
          push: false
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            GITHUB_TOKEN=${{ secrets.ACTION_TOKEN }}

      # Temp fix for local caches.
      #
      # Refer: https://github.com/docker/build-push-action/issues/252
      #        https://github.com/moby/buildkit/issues/1896
      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Lookup Images
        run: |
          docker image ls
