name: Test Application

on:
  pull_request:
    branches:
      - main

jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:18
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres:14.8
        ports: ['5432:5432']
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: Admin@1234
          POSTGRES_USER: postgres
          POSTGRES_DB: scraper
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      # - name: Migrate
      #   run: yarn migrate

      - name: Test
        run: yarn test
